FROM node:21-alpine3.18

WORKDIR /src/

COPY ./src /src
COPY ./.env /src
COPY ./package.json /src

RUN npm set strict-ssl false
RUN npm install pm2 -g && npm install

CMD NODE_OPTIONS=--max-old-space-size=8192 pm2-runtime start ecosystem.config.js --watch